version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

    groups:
      regular-updates:
        applies-to: version-updates
        update-types: ["patch", "minor"]
        dependency-type: production
      development-updates:
        applies-to: version-updates
        update-types: ["patch", "minor"]
        dependency-type: development
      security-patches:
        applies-to: security-updates
        update-types: ["patch"]