name: CI

on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'index.mjs'
      - 'bin/**'
      - 'package.json'
      - 'support/rollup.config.mjs'
      - 'support/specsplit.mjs'

  pull_request:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'index.mjs'
      - 'bin/**'
      - 'package.json'
      - 'support/rollup.config.mjs'
      - 'support/specsplit.mjs'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '24' ]

    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/setup@v2
      with:
        runtime: node@24
        cache: true


    - name: Test
      run: pnpm test

    - name: Upload coverage report to coveralls.io
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
