name: CI

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "index.mjs"
      - "bin/**"
      - "package.json"
      - "support/rollup.config.mjs"
      - "support/specsplit.mjs"
      - "pnpm-lock.yaml"

  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "index.mjs"
      - "bin/**"
      - "package.json"
      - "support/rollup.config.mjs"
      - "support/specsplit.mjs"
      - "pnpm-lock.yaml"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["24"]

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v3.0.0
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true

      - name: Test
        run: pnpm test

      - name: Upload coverage report to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
